#+title: UAV repülés tervezése
#+date: 2023. július 6.
#+author: Kalicz Péter
#+email: kalicz.peter@uni-sopron.hu
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:nil tasks:nil tex:t
#+options: timestamp:nil title:t toc:nil todo:t |:t
#+latex_class: article
#+latex_class_options: [a4paper]
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \usepackage[english,hungarian]{babel}
#+latex_header: \frenchspacing
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3)

Feladatomban az alább megadott paraméterekkel rendelkező repülés
végrehajtásához a tanszéken is rendelkezésre álló DJI Mavic Enterprise
családba tartozó /DJI Mavic 3M UAV/-t választottam.
A kiválasztott drónnal egy 1200 \cdot 600 m-es területet (lásd az [[fig:teroutline]]. ábrát) mérünk fel úgy, hogy
a képek terepi felbontása 2 cm;
a képek között átfedés ($p$) 85%-os;
a sorok közötti átfedés ($q$) 55%-os legyen.
A feladat végrehajtását a feladatkiírásnak megfelelően részletezem.

#+CAPTION[Vázlat]: A térképezendő terület vázlata
#+NAME:   fig:teroutline
[[file:simpleter.pdf]]


** Terület ábra                                                    :noexport:
#+header: :width 6 :height 6
#+begin_src R :file simpleter.pdf :results graphics file
library(sf)
library(ggplot2)
library(ggspatial)
ter <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,1200), szel = c(0,600)), coords = c("szel","mag"))))
# plot(ter, axes = TRUE)
ter.gg <- ggplot(data = ter) +
geom_sf() +
annotation_scale(location = "bl", width_hint = 0.4)
plot(ter.gg)
#+end_src

#+RESULTS:
[[file:simpleter.pdf]]


* A kiválasztott UAV ismertetése
A [[fig:DJIMavic3Moutline]]. ábrán látható DJI Mavic 3M UAV
specifikációját a honlapon közzétett adatok alapján adom meg
([[https://enterprise.dji.com/mavic-3-m/specs]]). Az eszköz
/maximális repülési ideje/ szélmentes körülmények között a
tengerszintről emelkedve, 100% töltöttségről indulva, állandó 9 m/s-os
(32.4 km/h) sebességgel repülve 43 perc. A /maximális repülési
távolság/ 32 km, /magasság/ 6000 m hasznos teher nélkül.Az emelkedés
és landolás /legfeljebb 12 m/s szélsebsség/ mellett történhet.  Az
opcionális RTK modul használatával 0.1 m pontosan tud navigálni
illesztőpontok használata nélkül. Az eszköz további előnyös
tulajdonsága, hogy a beépített szenzorainak köszönhetően előzetes
terepmodell nélkül képes az optimális repülési magasság
meghatározására. További előnye a kis méret és az összecsukhatóság,
amely a terepi feladatok megoldásánál hasznos tulajdonság.

#+CAPTION[DJI Mavic 3M]: DJI Mavic 3M UAV körvonalrajza
#+NAME:   fig:DJIMavic3Moutline
[[file:DJI_Mavic_3Moutline.pdf]]

* Az UAV-n található kamera
A háromtengelyű gimbalra szerelt kamera öt érzékelővel rendelkezik.
A lejebb bemutatott 20 MP-es 4/3 képarányú (RGB) kamera fölött négy
5MP-es kamera található (lásd a [[fig:DJIMavic3Moutline]]. ábrát),
amelyek távérzékelési célokra jól használható zöld, vörös, vörös edge
és közeli infra-vörös tartományokban készítenek képeket. Ez a blokk a felvételek
készítésénél nem használt, így a bemutatásától most eltekintek.

A felvételezés tervezéséhez figyelembe vett nagylátószögű főkamera
(RGB) érzékelője a gyenge fényviszonyok között is jó képet adó, nagy
méretű 3.3 \micro{}m-es pixelekkel rendelkezik. Az elmozdulás mentes
képek készítését támogató 0.7 másodperces intervallumú képkészítésre
alkalmas mechanikus elsütőberendezést építettek bele, amely a
légifényképezési feladatok gyors végrahajtását teszi lehetővé azáltal,
hogy a sebesség miatti elmosódás lehetőségét csökkenti. A térképezési
feladatok végrehajtásához a gimbal segítségével automatikusan készít
ferde-tengelyű felvételeket.

A gyártó által megadott adatok alapján a /képi pixelméret/
5280\cdot{}3956 pixel, a kamera /látószöge/ 84°, végül az /ekvivalens
fókusztávolság/ (c_{35}) 24 mm-es. A készülék GYIKjában közzétett
forrásból a kameraállandó (\(c\)) értéke 12.29 mm. Az eszközzel
készített kép EXIF információi alapján is a kamera állandó 12.29 mm. A
továbbiakban ez alapján fogom elvégezni a számításokat.

A szenzor mérete egy adatokat tartalmazó nem hivatalos oldalról
letöltve: 17.3 \cdot 13 mm.

A mellékletben található kameraparaméter számítás alapján a pixel mérete:

| A számítás alapja             | Pixelméret (\micro{}m) | Eltérés a 3.3 \micro{}m-től (nm) |
|-------------------------------+------------------------+----------------------------------|
| az egyenértékű fókusztávolság |                 3.3580 |                            58.21 |
| az érzékelő x oldala          |                 3.2765 |                           -23.48 |
| az érzékelő y oldala          |                 3.2861 |                           -22.16 |

A továbbiakban használom a felhasználói kézikönyvben megadott 3.3 \micro{}m-t.


* A tervezett repülés paraméterei
** Méretarány
\[a_k = \frac{res}{res'} =  6060.606 \text{, amelyből  } M_k = 1:6060\]
** Repülési magasság
\[h_0 = \frac{c / 1000}{a_k} = 74.5 \mathrm{m}\]

** Terepi képméret
\[S_x = s'_x \cdot a_k = 105.6 \mathrm{m, valamint  } S_y  = s'_x \cdot a_k = 79.12 \mathrm{m}\]

#+CAPTION[Vázlat]: A térképezendő terület és a kiszámított terepi képméret
#+NAME:   fig:terS
[[file:terS.pdf]]

** Terület ábra terepi képmérettel                                 :noexport:
#+header: :width 6 :height 6
#+begin_src R :file terS.pdf :results graphics file
  library(sf)
  library(ggplot2)
  library(ggspatial)
  ter <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,1200), szel = c(0,600)), coords = c("szel","mag"))))
  kep <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,79.12), szel = c(0,105.6)+600), coords = c("szel","mag"))))


  ter2 <- c(ter, kep)

  ter.gg <- ggplot(data = ter2) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.4)
  plot(ter.gg)
#+end_src

#+RESULTS:
[[file:terS.pdf]]


** Bázistávolság
\[B = S_y \cdot (1-p) =  11.868\,\mathrm{m}\]
** Sortávolság
\[A = S_x * (1-q) = 47.52\,\mathrm{m}\]
** Sorok száma
\[n_s = (H - Sy (2p-1))/ B + 1 = 97.4455\]
A sorok száma legyen 98. A számítást grafikusan ellenőriztem. Az eredmény a [[fig:tersorell]]. ábrán.

#+CAPTION[SorEll]: A sorok grafikus ellenőrzése
#+NAME:   fig:tersorell
[[file:tersorell.pdf]]

** Grafikus ellenőrzés bázis irány                                 :noexport:
#+header: :width 6 :height 6
#+begin_src R :file tersorell.pdf :results graphics file
  library(sf)
  library(ggplot2)
  library(ggspatial)
  ter <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,1200), szel = c(0,600)), coords = c("szel","mag"))))
  kep <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,79.12), szel = c(0,105.6)+600), coords = c("szel","mag"))))

  kepek <- c(kep, kep + c(0,11.868))

  for(szor in 2:97) {
      kepek <- c(kepek, kep + c(0, szor * 11.868))
  }

  ter2 <- c(ter, kepek - c(0, 11.868))

  ter.gg <- ggplot(data = ter2) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.4)
  plot(ter.gg)
#+end_src

#+RESULTS:
[[file:tersorell.pdf]]

** Képek száma
\[n_k = ( W - S_x) / A + 1 = 11.404\]

A bázis irányra merőlegesen tehát 12 képnek kell lennie. A számítást
grafikusan ellenőriztem. Az eredmény a [[fig:teroszlell]]. ábrán.

#+CAPTION[SorEll]: Az oszlopok grafikus ellenőrzése
#+NAME:   fig:teroszlell
[[file:teroszlell.pdf]]

** Grafikus ellenőrzés bázis irányra merőleges                     :noexport:
#+header: :width 6 :height 6
#+begin_src R :file teroszlell.pdf :results graphics file
  library(sf)
  library(ggplot2)
  library(ggspatial)
  ter <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,1200), szel = c(0,600)), coords = c("szel","mag"))))
  kep <- st_as_sfc(st_bbox(st_as_sf(data.frame(mag = c(0,79.12), szel = c(0,105.6)+600), coords = c("szel","mag"))))

  kepek <- c(kep, kep - c(47.52,0))

  for(szor in 2:11) {
      kepek <- c(kepek, kep - c(szor * 47.52, 0))
  }

  ter2 <- c(ter, kepek - c(105.6, 0))

  ter.gg <- ggplot(data = ter2) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.4)
  plot(ter.gg)
#+end_src

#+RESULTS:
[[file:teroszlell.pdf]]

** Összes kép
\[n_{sum} = n_s \cdot n_k = 1176\,\mathrm{db}\]
 
** Repülési sebesség, ha 2 mp-enként készítünk felvételeket
Először kiszámolom a feladatnak megfelelően.
\[v = \frac{B}{dt} = 5.934\,\frac{\mathrm{m}}{\mathrm{s}}\]

Ha kihasználjuk a DJI Mavic 3M képességeit a képeket 0.7 másodpercenként készíthetjük,
így a sebesség akár 16.95 m/s is lehetne, amelyet a drón még talán enyhén szeles időben
is tud, ugyanis 21 m/s a maximális sebessége haladási irányban, bár az EU
tagországokban ezt 19 m/s-ra korlátozzák, de még ez is több.

** A terület felméréséhez szükséges idő
Ehhez a repülési utat kell meghatározni először. A repülési hossz
\((n_s - 1) \cdot B = 1151.2\,\mathrm{m}\). Ezt n_k-szor tesszük meg
(\(n_k \cdot 1151.2\)), így 13\,814 m-t kell fényképezés idején
megtenni. Ehhez hozzáadjuk a sorok közötti utat (\((n_k - 1) \cdot
A\)), azaz 522.7 m-t. Tehát összesen kis kerekítéssel 14\,337 m-t kell
repülni fényképezés közben.

\[t = s / v = 2416 \mathrm{s}\]

A repülés idő tehát kicsivel több mint 40 perc, amit az UAV egy
feltöltéssel repülhetne (a specifikáció szerint 43 percet tud), de még
a felszállást és a leszállást is bele kell kalkulálni. Normál módban 6
m/s sebességgel emelkedhet és süllyedhet, ami a h_0 repülési magasság
eléréséhez és az ereszkedéshez 2\cdot 12 másodpercet hozzáad. Így a repülési
idő 41 percnek adódik, amit elméletileg tud a drón teljesíteni, de inkább
két részre bontva repülnék.

* Melléklet
** A kamera paraméterek számítása
#+NAME: sec:kamera
#+begin_src R
  ## Egyenértékű fókusztávolság
  c.35 <- 24
  ## Fókusztávolság
  c.real <- 12.29 #mm EXIF és GYIK
  ## A 35 mm film átlója
  s.35.atlo <- sqrt( 36 ^2 + 24^2)
  ## Valódi átló
  s.real.atlo <- s.35.atlo*c.real/c.35
  ## Érzékelő felbontás
  pix.x <- 5280
  pix.y <- 3956
  ## Képátló pixelben
  s.pix.atlo <- sqrt( pix.x ^2 + pix.y ^2)
  ## Pixelméret átlóból
  s.real.atlo/s.pix.atlo
  ## Pixelméret érzékelő méretből
  erz.x <- 17.3
  erz.y <- 13
  erz.x/pix.x
  erz.y/pix.y
#+end_src

** A repülés adatainak számítása
#+begin_src R
  ## Érzékelő pixelméret
  res.erz <- 0.0033 #mm a kézikönyvből 3.3 mikron
  ## Terepi felbontás
  res <- 0.02 #m a kiírásból
  ## Méretarányszám
  a.k <- res * 1000/res.erz # [1] 6060.606
  ## Fókusztávolság
  c.real <- 12.29 #mm a GYIK-ból és EXIFből
  ## Repülési magasság
  h.0 <- c.real/1000 * a.k # [1] 74.48485 m
  ## Érzékelő felbontás
  pix.x <- 5280
  pix.y <- 3956
  sv.x <- res.erz * pix.x # [1] 17.424 mm
  sv.y <- res.erz * pix.y # [1] 13.0548 mm
  ## Terepi képméret
  S.x <- sv.x * a.k / 1000 # [1] 105.6 m
  S.y <- sv.y * a.k / 1000 # [1] 79.12 m
  ## Százalékos átfedések
  p  <- 85/100 #% feladatból
  q <- 55/100 #% feladatból
  ## Bázisirányú átfedés
  B <- S.y * (1-p) # [1] 11.868 m
  ## Harántirányú átfedés
  A <- S.x * (1-q) # [1] 47.52 m
  ## Terület
  H <- 1200 #m feladatból
  W <- 600 #m feladatból
  ## Bázis irányú képszám
  ns <- (H - S.y * (2*p-1))/ B + 1 # [1] 97.44557 db
  ns <- 98 # db felfelé kerekítve
  ## Ellenőrzés
  (ns - 1) * B + S.y * (2 * p - 1) # [1] 1206.58 m
  ## Szélesség irányú képszém
  nk <- ( W - S.x) / A + 1 # [1] 11.40404 db
  nk <- 12 # db felfelé kerekítve
  ## Ellenőrzés
  (nk - 1) * A + S.x # [1] 628.32 m
  ## Összes kép
  ns * nk # [1] 1176 db
  ## A sebesség
  d.t <- 2 # másodperc a kiírásból
  v <- B/d.t # [1] 5.934 m/s
  d.t <- 0.7 # amit tud az UAV RGB-vel
  B/d.t # [1] 16.95429 m/s
  ## %epülési hossz
  (ns-1)*B
  1151.2*nk
  (nk - 1) * A
  13814 + 523 # [1] 14337 m

  (13814 + 523) / v # [1] 2416.077 s

  ## Emelkedés és süllyedés ideje
  h.0/6 # [1] 12.41414 s

  2416 + 2 * 12.4 # [1] 2440.8 s = 40.68 min
#+end_src

* 1. feladat. kiírás                                               :noexport:
** Hivatalos


UAV repülés tervezése

A feladat célja, hogy a hallgatók képesek legyenek egy UAV-vel történő
repülés főbb paramétereinek meghatározására.

A feladat megoldásához a következőkre van szükség:
1. Válasszunk ki egy aktuális, számunkra érdekes (’wanted’) kamerás
   UAV-t, amelynek a kamera-paraméterei jól dokumentáltak;
2. Egy 1200 m (É-D-i irányban) * 600 m (K-Ny-i irányban) területet
   szeretnénk úgy felmérni az eszközzel, hogy;
   a. a képek terepi felbontása 2 cm legyen;
   b. a képek között átfedés (p) legyen 85%-os;
   c. a sorok közötti átfedés (q) pedig legyen 55%-os.

*** Leadandók
- [X] A kiválasztott UAV ismertetése (pl. 
  - [X] repülési idő,
  - [X] max. távolság,
  - [X] max. magasság,
  - [X] max.  szélsebesség, stb.);
- [X] Az UAV-n található kamera részletesebb ismertetése (
  - [X] felbontás,
  - [X] c,
  - [X] képméret,
  - [X] látószög,
  - [X] képi pixelméret, stb.)
- [X] A tervezett repülés paramétereinek meghatározása:
  - [X] Repülési magasság (h 0 );
  - [X] Méretarány (M k );
  - [X] Tenrepi képméret (S x , S y );
  - [X] Bázistávolság (B);
  - [X] Sortávolság (A);
  - [X] Sorok száma (n s );
  - [X] Képek száma (n k );
  - [X] Összes kép (n sum );
  - [X] Repülési sebesség, ha 2 mp-enként készítünk felvételeket (v);
  - [X] A terület felméréséhez szükséges idő (t).

** Órán mondott

* org R                                                            :noexport:
https://github.com/erikriverson/org-mode-R-tutorial/blob/master/org-mode-R-tutorial.org alapján:
#+begin_src emacs-lisp :results silent
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((R . t)
     (latex . t)))
#+end_src

C-c C-c a blokkban!

C-c ' a külön szerkesztőben megnyitáshoz.

#+header: :width 8 :height 8 :R-dev-args bg="olivedrab", fg="hotpink"
#+begin_src R :file z.pdf :results graphics file
plot(matrix(rnorm(100), ncol=2), type="l")
#+end_src

#+RESULTS:
[[file:z.pdf]]

